CREATE TABLE CUSTOMER (
    ID   BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    NAME TEXT,
    AGE  INTEGER
);

INSERT INTO CUSTOMER (NAME, AGE) VALUES ('Michael Scott', 45);
INSERT INTO CUSTOMER (NAME, AGE) VALUES ('Dwight K Schrute', 40);

CREATE TABLE CUSTOMER_COUNTER (
    ID   BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    TOTAL  INTEGER
);
